#define DSKY_BARGRAPH_CTRL_PORT DDRD
#define DSKY_BARGRAPH_DATA_PORT PORTD
#define DSKY_BARGRAPH_PIN_B1 PD3
#define DSKY_BARGRAPH_PIN_B2 PD5
#define DSKY_BARGRAPH_PIN_B3 PD6

#define DSKY_DISPLAY_PIN_CLR PB1		// int sr_srclr    = 9;   // any free digital pin will do
#define DSKY_DISPLAY_PIN_PWRCLR PD2

#define DSKY_THRES_GLOC1 3
#define DSKY_THRES_GLOC2 6
#define DSKY_THRES_PWR1 0.15
#define DSKY_THRES_PWR2 0.10
#define DSKY_THRES_FUEL1 0.2
#define DSKY_THRES_FUEL2 0.1

#define DSKY_DISPLAY_INFOLIGHT_BIT_RESET 0
#define DSKY_DISPLAY_INFOLIGHT_BIT_INTERR 1
#define DSKY_DISPLAY_INFOLIGHT_BIT_OPRERR 2
#define DSKY_DISPLAY_INFOLIGHT_BIT_LGT 3
#define DSKY_DISPLAY_INFOLIGHT_BIT_RALT 4
//#define DSKY_DISPLAY_INFOLIGHT_BIT_ 5 // not assigned
#define DSKY_DISPLAY_INFOLIGHT_BIT_UPLINK 6
#define DSKY_DISPLAY_INFOLIGHT_BIT_GEAR 7
//#define DSKY_DISPLAY_INFOLIGHT_BIT_ 8 // not assigned
//#define DSKY_DISPLAY_INFOLIGHT_BIT_ 9 // not assigned
#define DSKY_DISPLAY_INFOLIGHT_BIT_PWR2 10
//#define DSKY_DISPLAY_INFOLIGHT_BIT_ 11 // not assigned
#define DSKY_DISPLAY_INFOLIGHT_BIT_PWR1 12
#define DSKY_DISPLAY_INFOLIGHT_BIT_GLOC2 13
//#define DSKY_DISPLAY_INFOLIGHT_BIT_ 14 // not assigned
#define DSKY_DISPLAY_INFOLIGHT_BIT_GLOC1 15
// #define DSKY_DISPLAY_INFOLIGHT_BIT_ 16 // not assigned
#define DSKY_DISPLAY_INFOLIGHT_BIT_FUEL2 17
#define DSKY_DISPLAY_INFOLIGHT_BIT_PROG 18
#define DSKY_DISPLAY_INFOLIGHT_BIT_BRK 19
#define DSKY_DISPLAY_INFOLIGHT_BIT_TEMP 20
#define DSKY_DISPLAY_INFOLIGHT_BIT_ALT2 21
#define DSKY_DISPLAY_INFOLIGHT_BIT_ALT1 22
#define DSKY_DISPLAY_INFOLIGHT_BIT_FUEL1 23
#define DSKY_DISPLAY_INFOLIGHT_BIT_RCS 24
#define DSKY_DISPLAY_INFOLIGHT_BIT_STBY 25
#define DSKY_DISPLAY_INFOLIGHT_BIT_VEL2 26
#define DSKY_DISPLAY_INFOLIGHT_BIT_VEL1 27
#define DSKY_DISPLAY_INFOLIGHT_BIT_NOUN 28
#define DSKY_DISPLAY_INFOLIGHT_BIT_VERB 29
#define DSKY_DISPLAY_INFOLIGHT_BIT_SAS 30
#define DSKY_DISPLAY_INFOLIGHT_BIT_KEYREL 31
